-- User table
CREATE TABLE USER (
    USERID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    VERIFYCODE VARCHAR(6),
    STATUS VARCHAR(25),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Store table
CREATE TABLE STORE (
    STOREID INT AUTO_INCREMENT PRIMARY KEY,
    STORENAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Receipt table
CREATE TABLE RECEIPT (
    RECEIPTID INT AUTO_INCREMENT PRIMARY KEY,
    STOREID INT,
    RECEIPT_BARCODE VARCHAR(255),
    RECEIPT_DATE DATE,
    FOREIGN KEY (STOREID) REFERENCES STORE(STOREID),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Item table
CREATE TABLE ITEM (
    ITEMID INT AUTO_INCREMENT PRIMARY KEY,
    RECEIPTID INT,
    ITEM_BARCODE VARCHAR(255),
    ITEM_NAME VARCHAR(255),
    BOUGHT_PRICE VARCHAR(255),
    SELL_PRICE VARCHAR(255),
    SHELF_LOCATION VARCHAR(50),
    WEIGHT VARCHAR(255),
    SIZE VARCHAR(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    BOUGHT_FROM_STORE VARCHAR(255),
    SOLD_FOR VARCHAR(255),
    FOREIGN KEY (RECEIPTID) REFERENCES RECEIPT(RECEIPTID)
);

-- Customer table
CREATE TABLE CUSTOMER (
    CUSTOMERID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    ADDRESS VARCHAR(255),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Sale table
CREATE TABLE SALE (
    SALEID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT,
    SALE_DATE DATE,
    SHIPPING_COST DECIMAL(10, 2),
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- SaleItem table (many-to-many relationship between Sale and Item)
CREATE TABLE SALEITEM (
    SALEID INT,
    ITEMID INT,
    QUANTITY INT,
    PRIMARY KEY (SALEID, ITEMID),
    FOREIGN KEY (SALEID) REFERENCES SALE(SALEID),
    FOREIGN KEY (ITEMID) REFERENCES ITEM(ITEMID)
);

-- Table to track overall stats
CREATE TABLE STATS (
    STATID INT AUTO_INCREMENT PRIMARY KEY,
    TOTAL_SPEND DECIMAL(10, 2),
    TOTAL_INCOME DECIMAL(10, 2),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



